book_info/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    path('api_book/', views.BookList.as_view()),
    path('api_author/<pk>', views.AuthorDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

book_info/book/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from book import views

app_name = 'book'

urlpatterns = [
    path('index/', TemplateView.as_view(template_name='book/index.html'),
         name='index'),
    path('book/<slug:slug>/', views.InfoCard.as_view(), {'list_type': 'book'},
         name='book'),
    path('book_list/', views.TotalList.as_view(),
         {'list_type': 'book_list'},
         name='book_list'),
    path('author_list/', views.TotalList.as_view(),
         {'list_type': 'author_list'},
         name='author_list'),
    path('genre_list/', views.TotalList.as_view(),
         {'list_type': 'genre_list'},
         name='genre_list'),
    path('author/<slug:slug>/',
         views.InfoCard.as_view(),
         {'list_type': 'author'},
         name='author'),
    path('search_book/', views.SearchBook.as_view(), name='search_book'),
    path('search_author/', views.SearchAuthor.as_view(), name='search_author'),
    path('search_genre/', views.SearchGenre.as_view(), name='search_genre'),
    path('book_create/', views.BookCreate.as_view(), name='book_create'),
    path('', include('reader.urls', namespace='reader')),
]

book_info/book_info/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('', include('reader.urls', namespace='reader')),
    path('', include('api.urls')),
]

book_info/reader/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from reader import views

app_name = 'reader'

urlpatterns = [
    path('reader_create/', views.ReaderCreate.as_view(), name='reader_create'),
    path('reader_list/', views.SearchReader.as_view(), name='reader_list'),
    path('reader_update/<slug:slug>/', views.ReaderUpdate.as_view(), name='reader_update'),
    path('reader_del/<slug:slug>/', views.ReaderDelete.as_view(), name='reader_del'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),

]

book_info/book/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    author_id = models.AutoField(primary_key=True)
    name = models.CharField('Имя', max_length=255)
    surname = models.CharField('Фамилия', max_length=255)
    date_birth = models.DateField('Дата рождения', blank=True, null=True)
    slug = models.SlugField(
        max_length=255,
        unique=True,
        null=False,
        blank=False)

    def __str__(self):
        return (self.name + ' ' + self.surname)


class Genre(models.Model):
    genre_id = models.AutoField(primary_key=True)
    name = models.CharField('Жанр', max_length=255)

    def __str__(self):
        return self.name


class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    title = models.CharField('Название', max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    author_id = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        related_name='author_book')
    genre_id = models.ManyToManyField(
        Genre,
        related_name='genre_book')
    publishing_house = models.CharField(
        'Издательство',
        max_length=255)
    year_publishing = models.IntegerField(
        'Год издания',
        blank=True,
        null=True)
    reader = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='reader_book',
        blank=True,
        null=True)

    def __str__(self):
        return self.title

book_info/book/forms.py
from django import forms
from book import models


class BookSearch(forms.Form):
    title = forms.CharField(label='Поиск по названию',
                            required=False,
                            help_text='Поиск по названию книги')
    year_publishing = forms.IntegerField(label='Год публикации',
                                         min_value=0, required=False,
                                         help_text='на-р 1990')
    publishing_house = forms.CharField(label='Издательство',
                                       required=False)
    author = forms.CharField(label='Автор',
                             required=False)

    def clean(self):
        author = self.cleaned_data['author']
        if author.isdigit():
            raise forms.ValidationError('Используй буквы')


class BookCreate(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'

book_info/book/views.py
from book import models, forms, filters
# from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView
from .models import Genre, Author, Book


class TitleMixin:
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_title()
        return context


class TotalList(TitleMixin, ListView):
    model = models.Book
    template_name = 'book/list.html'
    title = 'Список книг'

    def get_queryset(self):
        title = self.request.GET.get('title')
        qs = models.Book.objects.all()
        if title:
            return qs.filter(title__icontains=title)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.BookSearch(self.request.GET or None)
        list_type = self.kwargs['list_type']
        context['class_name'] = list_type

        if list_type == 'book_list':
            book_list = Book.objects.all()
            context['book_list'] = book_list
        elif list_type == 'author_list':
            author_list = Author.objects.all()
            context['author_list'] = author_list
        elif list_type == 'genre_list':
            genre_list = Genre.objects.all()
            context['genre_list'] = genre_list
        return context


class InfoCard(TitleMixin, DetailView):
    template_name = 'book/info_card.html'
    slug_url_kwarg = 'slug'

    def get_model(self):
        list_type = self.kwargs['list_type']
        if list_type == 'author':
            return models.Author
        else:
            return models.Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        list_type = self.kwargs['list_type']
        context['class_name'] = list_type

        if list_type == 'author':
            author = self.get_object()
            context['book_list'] = author.author_book.all()
            genre_list = set(
                Genre.objects.filter(
                    genre_book__author_id=author))
            context['genre_list'] = genre_list
        elif list_type == 'book':
            book = self.get_object()
            context['genre_list'] = book.genre_id.all()

        return context

    def get_queryset(self):
        model = self.get_model()
        queryset = model._default_manager.all()
        return queryset


class SearchBook(TitleMixin, ListView):
    model = models.Book
    template_name = 'book/search_book.html'
    title = 'Список книг'

    def get_filters(self):
        return filters.BookFilter(self.request.GET)

    def get_queryset(self):
        # title = self.request.GET.get('title')
        # year_publishing = self.request.GET.get('year_publishing')
        # publishing_house = self.request.GET.get('publishing_house')
        # author = self.request.GET.get('author')
        # qs = models.Book.objects.all()
        # filter_q = Q()
        # if title or year_publishing or publishing_house or author:
        #     if title:
        #         filter_q |= Q(title__icontains=title)
        #     if year_publishing:
        #         filter_q |= Q(year_publishing=year_publishing)
        #     if publishing_house:
        #         filter_q |= Q(publishing_house__icontains=publishing_house)
        #     if author:
        #         author_parts = author.split()
        #         for part in author_parts:
        #             filter_q |= Q(author_id__name__icontains=part)
        #             filter_q |= Q(author_id__surname__icontains=part)
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filters()
        return context


class SearchAuthor(TitleMixin, ListView):
    model = models.Author
    template_name = 'book/search_author.html'
    title = 'Список авторов'

    def get_queryset(self):
        title = self.request.GET.get('title')
        qs = models.Author.objects.all()
        if title:
            return qs.filter(title__icontains=title)
        print("Title:", title)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.BookSearch(self.request.GET or None)
        print(context)
        return context


class SearchGenre(TitleMixin, ListView):
    model = models.Genre
    template_name = 'book/search_genre.html'
    title = 'Список жанров'

    def get_queryset(self):
        title = self.request.GET.get('title')
        qs = models.Genre.objects.all()
        if title:
            return qs.filter(title__icontains=title)
        print("Title:", title)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.BookSearch(self.request.GET or None)
        print(context)
        return context


class BookCreate(TitleMixin, CreateView):
    model = models.Book
    template_name = 'book/book_create.html'
    form_class = forms.BookCreate
    success_url = reverse_lazy('book:book_list')

book_info/book/templates/book/add.html
{% extends 'lib/base.html'%}
{% block content %}
<!--<form action="{% url 'lib:author_create' %}" method="POST">-->
    {% csrf_token %}
    {{ form.name.label_tag }}
    {{ form.name }}
    {{ form.surname.label_tag }}
    {{ form.surname }}
    {{ form.data_birth.label_tag }}
    {{ form.data_birth }}
    {{ form.slug.label_tag }}
    {{ form.slug }}
    {{ form.first_name.errors }}
    <button type="submit">Добавить</button>
<!--</form>-->
{% endblock %}

book_info/book/templates/book/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Book Info</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
<body>
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="/index"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'book:index' %}" class="nav-link px-2 text-white">Главная</a></li>
          <li><a href="{% url 'book:book_list' %}" class="nav-link px-2 text-white">Книги</a></li>
          <li><a href="{% url 'book:author_list' %}" class="nav-link px-2 text-white">Авторы</a></li>
          <li><a href="{% url 'book:genre_list' %}" class="nav-link px-2 text-white">Жанры</a></li>
          {% if request.user.is_superuser %}
          <li><a href="{% url 'reader:reader_create' %}" class="nav-link px-2 text-white">Добавить читателя</a></li>
          <li><a href="{% url 'book:book_create' %}" class="nav-link px-2 text-white">Добавить книгу</a></li>
          <li><a href="{% url 'reader:reader_list' %}" class="nav-link px-2 text-white">Список читателей</a></li>
          {% endif %}
        </ul>
        {% if request.user.is_superuser %}
        <div class="text-end">
         <form method="POST" action="{% url 'reader:logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-light me-2">Выйти</button>
        </form>
          {% else %}
          <form method="POST" action="{% url 'reader:login' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-light me-2">Войти</button>
            </form>
          {% endif %}
        </div>
      </div>
    </div>
  </header>
    <div class="text-bg-light p-3">
    {% block content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</div>
</html>

book_info/book/templates/book/book_create.html
{% extends 'book/base.html'%}
{% block content %}
<form action="{% url 'book:book_create' %}" method="POST">
    {% csrf_token %}
    {{ form.title.label_tag }}
    {{ form.title }}
    {{ form.title.errors }}
    {{ form.slug.label_tag }}
    {{ form.slug }}
    {{ form.slug.errors }}
    {{ form.author_id.label_tag }}
    {{ form.author_id }}
    {{ form.author_id.errors }}
    {{ form.genre_id.label_tag }}
    {{ form.genre_id }}
    {{ form.genre_id.errors }}
    {{ form.publishing_house.label_tag }}
    {{ form.publishing_house }}
    {{ form.publishing_house.errors }}
    {{ form.year_publishing.label_tag }}
    {{ form.year_publishing }}
    {{ form.year_publishing.errors }}

    <button type="submit">Добавить</button>
</form>
{% endblock %}
}

book_info/book/templates/book/index.html
{% extends 'book/base.html'%}
{% block content %}
  <body>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Книги</h5>
    <p class="card-text">Найди себе приключение</p>
    <a href="{% url 'book:search_book' %}" class="btn btn-primary">Искать книгу</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Авторы</h5>
    <p class="card-text">Найди своего наставника</p>
    <a href="{% url 'book:search_author' %}" class="btn btn-primary">Искать автора</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Жанры</h5>
    <p class="card-text">ЖАНРЫ! </p>
    <a href="{% url 'book:search_genre' %}" class="btn btn-primary">Жанры!!!</a>
  </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
{% endblock %}

book_info/book/templates/book/info_card.html
{% extends 'book/base.html'%}
{% block content %}
{% if class_name == 'book' %}
      <dl class="row">
        <dt class="col-sm-3">Название</dt>
        <dd class="col-sm-9">{{book.title}}</dd>
        <dt class="col-sm-3">Автор</dt>
        <dd class="col-sm-9">{{book.author_id}}</dd>
        <dt class="col-sm-3">Жанр</dt>
        <dd class="col-sm-9">
          {% for genre in genre_list %}
            {{ genre.name }}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </dd>
      </dl>
 {% elif class_name == 'author' %}
<dl class="row">
        <dt class="col-sm-3">Имя</dt>
        <dd class="col-sm-9">{{author.name}}</dd>
        <dt class="col-sm-3">Фамилия</dt>
        <dd class="col-sm-9">{{author.surname}}</dd>
        <dt class="col-sm-3">Дата рождения</dt>
          <dd class="col-sm-9">{{author.date_birth}}</dd>
          <dt class="col-sm-3">Книги</dt>
        <dd class="col-sm-9">
          {% for book in book_list %}
            {{ book.title }}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </dd>
          <dt class="col-sm-3">Жанр</dt>
        <dd class="col-sm-9">
          {% for genre in genre_list %}
            {{ genre.name }}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </dd>
      </dl>
{% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
{% endblock %}

book_info/book/templates/book/list.html
{% extends 'book/base.html'%}
{% block content %}
{% if class_name == 'book_list' %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">book_id</th>
      <th scope="col">Название</th>
      <th scope="col">Автор</th>
      <th scope="col">Издательство</th>
      <th scope="col">Год издания</th>
    </tr>
  </thead>
  <tbody>
        {% for book in book_list %}
    <tr>
      <th scope="row">{{ book.book_id }}</th>
      <td><a href="{% url 'book:book' slug=book.slug %}">{{book.title}}</a></td>
      <td><a href="{% url 'book:author' slug=book.author_id.slug %}">{{book.author_id}}</a></td>
      <td>{{book.publishing_house}}</td>
      <td>{{book.year_publishing}}</td>
    </tr>
  {% endfor %}
        </tbody>
  {% elif class_name == 'author_list' %}
  <table class="table">
  <thead>
    <tr>
      <th scope="col">author_id</th>
      <th scope="col">Имя</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Дата Рождения</th>
    </tr>
  </thead>
  <tbody>
  {% for author in author_list %}
  <tr>
  <th scope="row">{{ author.author_id }}</th>
      <td>{{author.name}}</td>
      <td>{{author.surname}}</td>
      <td>{{author.date_birth}}</td>
    </tr>
  {% endfor %}
  </tbody>
  {% elif class_name == 'genre_list' %}
    <table class="table">
  <thead>
    <tr>
      <th scope="col">genre_id</th>
      <th scope="col">Название</th>
    </tr>
  </thead>
  <tbody>
  {% for genre in genre_list %}
  <tr>
   <th scope="row">{{ genre.genre_id }}</th>
      <td>{{genre.name}}</td>
    </tr>
  {% endfor %}
  {% endif %}
  </tbody>
</table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
{% endblock %}

book_info/book/templates/book/search_author.html
{% extends 'book/base.html'%}
{% block content %}
    <form method="GET">
    {{ form }}
    <button type="submit">Поиск</button>
  </form>
 <table class="table">
  <thead>
    <tr>
      <th scope="col">author_id</th>
      <th scope="col">Имя</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Дата Рождения</th>
    </tr>
  </thead>
  <tbody>
  {% for author in author_list %}
  <tr>
  <th scope="row">{{ author.author_id }}</th>
      <td>{{author.name}}</td>
      <td>{{author.surname}}</td>
      <td>{{author.date_birth}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
{% endblock %}

book_info/book/templates/book/search_book.html
{% extends 'book/base.html'%}
{% block content %}
    <form method="GET">
    {{ filter.form.as_p }}
    <button type="submit">Поиск</button>
  </form>
<table class="table">
  <thead>
    <tr>
      <th scope="col">book_id</th>
      <th scope="col">Название</th>
      <th scope="col">Автор</th>
      <th scope="col">Издательство</th>
      <th scope="col">Год издания</th>
    </tr>
  </thead>
  <tbody>
        {% for book in book_list %}
    <tr>
      <th scope="row">{{ book.book_id }}</th>
      <td><a href="{% url 'book:book' slug=book.slug %}">{{book.title}}</a></td>
      <td><a href="{% url 'book:author' slug=book.author_id.slug %}">{{book.author_id}}</a></td>
      <td>{{book.publishing_house}}</td>
      <td>{{book.year_publishing}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
{% endblock %}

book_info/book/templates/book/search_genre.html
{% extends 'book/base.html'%}
{% block content %}
    <form method="GET">
    {{ form }}
    <button type="submit">Поиск</button>
  </form>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">genre_id</th>
      <th scope="col">Название</th>
    </tr>
  </thead>
  <tbody>
  {% for genre in genre_list %}
  <tr>
   <th scope="row">{{ genre.genre_id }}</th>
      <td>{{genre.name}}</td>
    </tr>
  {% endfor %}
   </tbody>
</table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
{% endblock %}