book_info/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    path('api_book/', views.BookList.as_view()),
    path('api_author/<pk>', views.AuthorDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

book_info/book_info/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='book')),
    path('', include('reader.urls', namespace='reader')),
    path('', include('api.urls')),
]

book_info/reader/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from reader import views

app_name = 'reader'

urlpatterns = [
    path('reader_create/', views.ReaderCreate.as_view(), name='reader_create'),
    path('reader_list/', views.SearchReader.as_view(), name='reader_list'),
    path('reader_update/<slug:slug>/', views.ReaderUpdate.as_view(), name='reader_update'),
    path('reader_del/<slug:slug>/', views.ReaderDelete.as_view(), name='reader_del'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),

]

book_info/reader/models.py
from django.db import models


class Reader(models.Model):
    name = models.CharField('Имя', max_length=255)
    surname = models.CharField('Фамилия', max_length=255)
    date_birth = models.DateField('Дата рождения', blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, null=False, blank=False)

    def __str__(self):
        return (self.name + ' ' + self.surname)

book_info/reader/forms.py
from django import forms
from reader import models


class ReaderSearch(forms.Form):
    name = forms.CharField(label='Имя', required=False)
    surname = forms.CharField(label='Фамилия', required=False)
    date_birth = forms.DateField(label='Дата рождения', required=False)

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        surname = cleaned_data.get('surname')

        if name.isdigit() or surname.isdigit():
            raise forms.ValidationError('Используй буквы')

        return cleaned_data


class ReaderCreate(forms.ModelForm):
    class Meta:
        model = models.Reader
        fields = '__all__'

book_info/reader/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from reader import models, forms
from django.shortcuts import redirect
from django.urls import reverse


class TitleMixin:
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_title()
        return context


class ReaderCreate(TitleMixin, CreateView):
    model = models.Reader
    template_name = 'reader/reader_create.html'
    form_class = forms.ReaderCreate
    success_url = reverse_lazy('reader:reader_list')


class SearchReader(TitleMixin, ListView):
    model = models.Reader
    template_name = 'reader/reader_list.html'
    title = 'Список читателей'

    def get_queryset(self):
        name = self.request.GET.get('name')
        qs = models.Reader.objects.all()
        if name:
            return qs.filter(name__icontains=name)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.ReaderSearch(self.request.GET or None)
        return context


class ReaderUpdate(TitleMixin, UpdateView):
    model = models.Reader
    template_name = 'reader/reader_create.html'
    fields = '__all__'
    success_url = reverse_lazy('reader:reader_list')


class ReaderDelete(TitleMixin, DeleteView):
    model = models.Reader
    template_name = 'reader/reader_del.html'
    success_url = reverse_lazy('reader:reader_list')


class UserLogin(TitleMixin, View):
    template_name = 'reader/login.html'

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/index')
        return render(request, self.template_name)

    def get(self, request):
        return render(request, self.template_name)

def user_logout(request):
    logout(request)
    return redirect('/index')

book_info/reader/templates/reader/login.css.html
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }

book_info/reader/templates/reader/login.html
{% extends 'book/base.html'%}
{% block content %}
<form method="post" action="{% url 'reader:login' %}">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Пожалуйста, введите ваш логин и пароль</h1>

    <div class="form-floating">
        <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Login">
        <label for="floatingInput">Ваш логин</label>
    </div>
    <div class="form-floating">
        <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Ваш пароль</label>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">Войти</button>
</form>
{% endblock %}

book_info/reader/templates/reader/reader_create.html
{% extends 'book/base.html'%}
{% block content %}
<form action="{% url 'reader:reader_create' %}" method="POST">
    {% csrf_token %}
    {{ form.name.label_tag }}
    {{ form.name }}
    {{ form.name.errors }}
    {{ form.surname.label_tag }}
    {{ form.surname }}
    {{ form.surname.errors }}
    {{ form.date_birth.label_tag }}
    {{ form.date_birth }}
    {{ form.date_birth.errors }}
    {{ form.slug.label_tag }}
    {{ form.slug }}
    {{ form.slug.errors }}

    <button type="submit">Добавить</button>
</form>
{% endblock %}

book_info/reader/templates/reader/reader_del.html
{% extends 'book/base.html'%}
{% block content %}
<form action="{% url 'reader:reader_del' slug=reader.slug %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <p>Удалить читателя {{ reader.name }} {{ reader.surname }}?</p>
    <button type="submit">Удалить</button>
    <button type="reset">Отмена</button>
</form>
{% endblock %}

book_info/reader/templates/reader/reader_list.html
{% extends 'book/base.html'%}
{% block content %}
    <form method="GET">
    {{ form }}
    <button type="submit">Поиск</button>
  </form>
 <table class="table">
  <thead>
    <tr>
      <th scope="col">номер читательского билета</th>
      <th scope="col">Имя</th>
      <th scope="col">Фамилия</th>
      <th scope="col">Дата Рождения</th>
      <th scope="col">slug</th>
      <th scope="col">Обновить</th>
      <th scope="col">Удалить</th>
    </tr>
  </thead>
  <tbody>
  {% for reader in reader_list %}
  <tr>
      <th scope="row">{{ reader.id }}</th>
      <td>{{reader.name}}</td>
      <td>{{reader.surname}}</td>
      <td>{{reader.date_birth}}</td>
      <td>{{reader.slug}}</td>
      <td><a href="{% url 'reader:reader_update' slug=reader.slug %}">Обновить</a></td>
      <td><a href="{% url 'reader:reader_del' slug=reader.slug %}">Удалить</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
{% endblock %}

book_info/reader/templates/reader/reader_update.html
{% extends 'book/base.html'%}
{% block content %}
<form action="{% url 'reader:reader_update' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}